version: "2"
services:
    modafoca:
        build: .
        command: gulp serve
        volumes:
            # Mounts the project directory to update the host with changes made
            # inside the container, such as node_modules/ and package-lock.json
            - './:/usr/modafoca/'
        ports:
            - 3000:3000
    db:
        image: postgres:10.2-alpine
        restart: always
        environment:
            POSTGRES_DB: fatos
            PGDATA: /var/lib/postgresql/data/fatos/
            POSTGRES_PASSWORD: must be changed.
        ports:
            - 5432:5432
        volumes:
            - /var/lib/postgresql/data/fatos/
