version: "2"
services:
    memoria:
        build: .
        # The volume below overrides the COPY commands from the Dockerfile.
        # So, install node dependencies again before serving.
        command: bash -c "npm install && node node_modules/gulp/bin/gulp.js serve"
        volumes:
            # Mounts the project directory to update the host with changes made
            # inside the container, such as node_modules/ and package-lock.json
            - ./:/usr/memoria-politica/
        links:
            - db
        ports:
            - 3000:3000
    db:
        image: postgres:10.2-alpine
        restart: always
        environment:
            POSTGRES_DB: fatos
            PGDATA: /var/lib/postgresql/data/fatos/
            POSTGRES_PASSWORD: must be changed.
        ports:
            - 5432:5432
        volumes:
            - fatos:/var/lib/postgresql/data/fatos
volumes:
    fatos:
